// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeeKer.Crafty.Infrastructure.Persistence;

#nullable disable

namespace ZeeKer.Crafty.Infrastructure.Migrations
{
    [DbContext(typeof(TelegramBotDbContext))]
    [Migration("20250930153204_InitialChatState")]
    partial class InitialChatState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ZeeKer.Crafty.Infrastructure.Persistence.Entities.TelegramChatStateEntity", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("TelegramChatStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
